#!/bin/python

import subprocess
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import sys
import os

### Need one argument: the path of the folder with hist.txt files generated by " bedtools covergae ... | grep 'all' " 

fig = plt.figure(1)
ax = plt.subplot(111)

for file in os.listdir(sys.argv[1]):
    f=open(sys.argv[1]+file,"r")
    x=[]
    y=[]
    cumul = 0
    for line in f:
        field=line.split("\t")
        if int(field[1]) < 150:
            x.append(field[1])
            cumul += float(field[4][:-2])
            y.append(1-cumul)
        else:
            break
    ax.plot(x,y,label=file[:-9])
    f.close()
	
box = ax.get_position()
ax.set_position([box.x0, box.y0 + box.height * 0.1,
                 box.width, box.height * 0.9])

plt.title('Exome coverage')
plt.xlabel('Sequencing Depth')
plt.ylabel('Cumulative genome coverage')
plt.xlim([0,150])
plt.xticks([10,20,30,50,100,150])
plt.yticks([0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1])
for i in [10,20,30]:
    plt.axvline(x=i,linewidth=0.5, color='0.2')

ax.legend(loc='upper center', bbox_to_anchor=(0.5, -0.1), ncol=5, fancybox=True)

plt.savefig(sys.argv[1]+"exome_coverage.pdf")
